
leg:
  link1_length: 1 # hip
  link2_length: 2.5 # thigh
  link3_length: 2 # shin

joint_limits: # TO BE UPDATED
  hip: [-90, 90] 
  thigh: [-90, 90]
  shin: [0, 135]

body:
  width: 10
  length: 20
  height: 6

walking:
  deg_per_sec: 10
  max_step_height_pct: 0.2
  step_length_deg: 30 # with leg fully straight, degree rotated forward for max step length
  LF_phase_offset: 0 # left front leg phase offset in degrees
  RF_phase_offset: 180 # right front leg phase offset in degrees
  LB_phase_offset: 180 # left back leg phase offset in degrees
  RB_phase_offset: 0 # right back leg phase offset in degrees

control:
  control_hz: 50 # control loop frequency in Hz

neutral_stance:
  neutral_stance_height_pct: 0.7 # percentage of straight leg height